name: Deploy to AWS

on:
  push:
    branches:
      - main  # 任意のブランチでOK
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '24'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: us-east-1

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - uses: flatt-security/setup-takumi-guard-npm@v1

      - name: Install dependencies
        run: npm ci

      - name: Build TypeScript code
        run: npm run build

      - name: Synthesize CloudFormation template
        run: npx cdk synth

      - name: Deploy to AWS
        run: npx cdk deploy -c slackReactions=thumbsup,tada,rocket,inoki,toukon,toukon,qiitan-ponpon --require-approval never

      - name: Garbage collect old CDK assets
        run: npx cdk gc --unstable=gc --confirm false
